In [1]:
import pandas as pd
import numpy as np

In [1]:
import pandas as pd

data1 = pd.read_csv("StudentsPerformance.csv")
print(data1.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [2]:
data1.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
data1["parental level of education"].unique()

<StringArray>
[ 'bachelor's degree',       'some college',    'master's degree',
 'associate's degree',        'high school',   'some high school']
Length: 6, dtype: str

In [8]:
print(data1.columns)

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [ ]:
data1.groupby('parental level of education')

In [4]:
data1.rename(columns={'race/ethnicity': 'groups'}, inplace=True)
data1

,gender,groups,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [12]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race and ethnicity           1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [13]:
data1.rename(columns={'race/ethnicity':'groups'},inplace=True)

In [2]:
import pandas as pd

data1 = pd.read_csv("StudentsPerformance.csv")
print(data1.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [5]:
groups=data1.groupby("groups")

In [6]:
groups["writing score"].mean(numeric_only=True).sort_values().head(1)

groups
group A    62.674157
Name: writing score, dtype: float64

In [7]:
groups["math score"].sum(numeric_only=True).sort_values()\
.tail()

groups
group A     5485
group E    10335
group B    12056
group D    17649
group C    20564
Name: math score, dtype: int64

In [9]:
data1.columns

Index(['gender', 'groups', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [13]:
print(data1.columns)

Index(['gender', 'groups', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [15]:
groups = data1.groupby('test preparation course')
groups['writing score'].mean()

test preparation course
completed    74.418994
none         64.504673
Name: writing score, dtype: float64

In [22]:
gp=data1.groupby('parental level of education')
gp['reading score'].sum(numeric_only=True).sort_values().tail(1)

parental level of education
associate's degree    15746
Name: reading score, dtype: int64

In [23]:
data1.groupby('parental level of education').groups

{'associate's degree': [3, 5, 10, 11, 19, 35, 36, 38, 39, 40, 41, 42, 44, 45, 46, 48, 51, 56, 57, 62, 63, 68, 69, 72, 75, 80, 83, 87, 93, 95, 102, 107, 108, 110, 112, 121, 138, 147, 149, 152, 158, 159, 160, 173, 177, 183, 185, 190, 195, 200, 202, 203, 213, 216, 221, 224, 231, 235, 239, 245, 246, 256, 257, 268, 272, 285, 286, 290, 295, 297, 299, 302, 303, 304, 308, 310, 313, 317, 319, 328, 331, 332, 333, 337, 343, 349, 353, 356, 375, 380, 381, 387, 393, 397, 406, 407, 409, 412, 417, 420, ...], 'bachelor's degree': [0, 24, 27, 60, 77, 90, 99, 101, 114, 116, 117, 120, 129, 134, 135, 148, 151, 153, 165, 174, 189, 199, 206, 232, 234, 236, 241, 266, 270, 275, 279, 282, 288, 293, 311, 312, 314, 318, 334, 347, 350, 355, 365, 367, 374, 379, 386, 414, 416, 426, 455, 456, 458, 460, 464, 475, 476, 493, 507, 509, 522, 528, 535, 538, 551, 562, 564, 566, 569, 571, 582, 587, 592, 594, 595, 612, 616, 617, 621, 624, 632, 645, 667, 692, 697, 700, 702, 705, 740, 748, 757, 771, 773, 784, 809, 816, 817, 821, 831, 832, ...], 'high school': [8, 9, 12, 16, 20, 28, 47, 49, 53, 55, 81, 84, 91, 92, 103, 111, 115, 123, 125, 137, 143, 156, 163, 166, 168, 170, 176, 182, 186, 197, 207, 212, 214, 217, 218, 220, 227, 240, 242, 247, 248, 249, 254, 263, 264, 267, 277, 280, 281, 294, 298, 309, 315, 320, 321, 324, 330, 340, 341, 342, 345, 348, 360, 366, 388, 395, 396, 403, 404, 408, 415, 419, 421, 431, 432, 438, 441, 447, 448, 459, 467, 468, 471, 480, 483, 485, 494, 495, 506, 519, 524, 527, 534, 537, 540, 547, 548, 568, 573, 574, ...], 'master's degree': [2, 14, 18, 25, 29, 32, 79, 106, 128, 130, 162, 164, 167, 175, 178, 180, 194, 225, 253, 259, 316, 377, 382, 389, 410, 422, 478, 500, 504, 508, 514, 523, 544, 549, 557, 567, 579, 600, 604, 607, 618, 685, 713, 735, 752, 781, 789, 812, 845, 846, 850, 861, 892, 900, 901, 940, 941, 957, 995], 'some college': [1, 4, 6, 7, 13, 21, 22, 26, 30, 31, 33, 34, 43, 50, 52, 58, 67, 70, 71, 82, 85, 86, 88, 94, 97, 98, 100, 104, 105, 113, 119, 122, 124, 127, 132, 133, 139, 141, 142, 144, 145, 155, 157, 161, 169, 172, 181, 191, 193, 198, 201, 204, 208, 209, 211, 226, 229, 230, 238, 243, 251, 255, 258, 261, 269, 271, 273, 274, 283, 300, 305, 306, 322, 325, 326, 327, 335, 344, 346, 351, 352, 354, 357, 358, 359, 362, 364, 370, 371, 373, 385, 391, 392, 401, 402, 411, 418, 424, 425, 435, ...], 'some high school': [15, 17, 23, 37, 54, 59, 61, 64, 65, 66, 73, 74, 76, 78, 89, 96, 109, 118, 126, 131, 136, 140, 146, 150, 154, 171, 179, 184, 187, 188, 192, 196, 205, 210, 215, 219, 222, 223, 228, 233, 237, 244, 250, 252, 260, 262, 265, 276, 278, 284, 287, 289, 291, 292, 296, 301, 307, 323, 329, 336, 338, 339, 361, 363, 368, 369, 372, 376, 378, 383, 384, 390, 394, 398, 399, 400, 405, 413, 423, 427, 428, 429, 433, 434, 439, 442, 444, 445, 473, 488, 498, 505, 511, 512, 513, 515, 518, 526, 531, 545, ...]}

In [25]:
data1.groupby('gender').ngroups

2